logging:
  config: src/main/resources/config/logback-spring.xml
server:
  port: ${port:8085}
spring:
  datasource:
    url: jdbc:mysql://192.168.0.46:3306/UrlEncoder?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: betaUser
    password: betaUser    
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
