logging:
  config: src/main/resources/config/logback-spring.xml
server:
  port: ${port:8085}
spring:
  datasource:
    url: jdbc:mysql://10.223.241.146:3306/UrlEncoder?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: serv_urlEncoder
    password: 9GKe9F6RtQQJcFQb
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
